### PR TITLE
Version Stabilization: Update version.json to 2.10

### PR DESCRIPTION
**Pull request by RyanToth3**

### CODE REVIEW

**Comment by RyanToth3** [comment]
@AArnott @javierdlg I'm not sure how to assign folks to PR in this repo, its not giving me an option to?

**Comment by AArnott** [comment]
@RyanToth3 That's probably because this isn't a Microsoft repo. :)

Why do we need a stable version? We just took changes to some sensitive areas that I don't personally fully understand and would like to change further. I feel some unstable version time reflects the potential instability of the library at the moment.

**Comment by RyanToth3** [comment]
@AArnott I'm just following the version stabalization wiki since we're going to be moving into 17.5 preview 4 at the end of the month. I wanted to get an early start on this since most folks are going to be out the second half of december.

If this doesn't need to be done I can cancel my PRs.

**Comment by AArnott** [comment]
Hmmm... I wonder if we can get away with it because AFAIK the only reason VSW needs a version beyond the latest stable version is for the NPM package, which isn't subject to the VS SDK stabilization rules. Can we forego this PR in favor of DevCore using the latest stable version instead, and only taking the prerelease of the NPM package, if that is required?

**Comment by RyanToth3** [comment]
DevCore doesn't have an explicit package reference for Nerdbank.Streams, we pull it in from StreamJsonRpc. And actually looking at StreamJsonRpc, it is already referencing a stable Nerdbank.Streams so we wouldn't actually need to make this update then.

I'll close the PR.

**Pull request closed without merging**
