### PR TITLE
Add `SequenceReader<T>` for netstandard2.0 projects

### LINKED ISSUE #433: Include copy of SequenceReader in netstandard2.0 build.
`SequenceReader<T>` is only available netstandard2.1+.
That means it is not available for .NET Framework.

Could the netstandard2.0 build of this library include a copy of `SequenceReader<T>`?

See https://github.com/dotnet/standard/issues/1493.

### PR DESCRIPTION
**Pull request by AArnott**
It uses a type forwarder on `netstandard2.1` so that we avoid type name conflicts when the BCL type _is_ available and (more importantly) everyone that is running on netstandard2.1 or later (whether they compiled against netstandard2.0 or not) will run against the BCL implementation of the type instead of our own.

Closes #433

### CODE REVIEW

**Comment by tmds** [comment]
> It uses a type forwarder on netstandard2.1 so that we avoid type name conflicts when the BCL type is available

@AArnott for my education: if there were no type forwarder, and only the netstandard2.0 build includes the type, how can there be a name conflict?

**Comment by AArnott** [comment]
There would be no name conflict in that case, but that would cause a much bigger problem. For those netstandard2.0 libraries that compile against this library, they would bind to _our_ type. At runtime in a .NET Standard 2.**1** application where the netstandard2.1 build of this library were deployed, all the other libraries that built against the netstandard2.0 build of this library would then throw a TypeLoadException.

By adding the TypeForwardedToAttribute to our netstandard2.1 build, the runtime will gracefully redirect instead of throwing.

**Comment by tmds** [comment]
Thanks. That makes sense.

I've started using the library and I encounter an issue because the `SequenceReader` API that is included in the library is larger than what is available in `netstandard2.1`. For example, `UnreadSequence` is not available.

**Comment by AArnott** [comment]
Oh dear. Good call. We'll have to fix that by either:
1. removing the API that isn't in netstandard2.1
2. only redirecting to the net5.0 one, leaving netstandard2.1 to run with our copy. 

Option 2 brings back the type name collision problem, so I think we'll have to go with option 1.

**Pull request merged**
